// Generated by CoffeeScript 1.8.0
(function() {
  var hideOverlay, showOverlay;

  showOverlay = function() {
    $('#overlay-dark,#popover-outer').css('display', 'block');
    return setTimeout(function() {
      return $('#overlay-dark,#popover-outer').addClass('selected');
    }, 50);
  };

  hideOverlay = function() {
    $('#overlay-dark,#popover-outer').removeClass('selected');
    return setTimeout(function() {
      return $('#overlay-dark,#popover-outer').css('display', 'none');
    }, 300);
  };

  $(function() {
    var families, initialize, map, markers, trails;
    map = null;
    families = {};
    trails = {};
    markers = [];
    initialize = function() {
      var openInfoWindow;
      map = new google.maps.Map($('#map-canvas')[0], {
        center: {
          lat: -33.886204,
          lng: 151.189005
        },
        zoom: 19,
        disableDefaultUI: true,
        mapTypeId: google.maps.MapTypeId.SATELLITE
      });
      openInfoWindow = null;
      $.get("json/families.json", function(json) {
        var familiesSorted;
        families = jQuery.extend(true, {}, json);
        familiesSorted = [];
        _.each(json, function(family, familyName) {
          familiesSorted.push(familyName);
          families[familyName]['markers'] = [];
          return _.each(family, function(species, key) {
            $('#menu-content-list').append("<div class=\"list-row\"><div class=\"text\"><div class=\"title\">" + key + "</div><div class=\"subtitle\">" + species.commonName + "</div></div><img src=\"/assets/images/disclosure-indicator.png\" class=\"disclosure-indicator\"></div>");
            if (!species.mapPin) {
              return;
            }
            return _.each(species.mapPin.replace(/[\(|\)]/g, '').split('; '), function(coords) {
              var coordsSplit, infoWindow, marker;
              coordsSplit = coords.split(", ");
              infoWindow = new google.maps.InfoWindow({
                content: species.genusSpecies
              });
              marker = new google.maps.Marker({
                position: new google.maps.LatLng(coordsSplit[0], coordsSplit[1]),
                map: map,
                title: species.genusSpecies
              });
              markers.push({
                species: species.genusSpecies.toLowerCase(),
                marker: marker
              });
              families[familyName]['markers'].push(marker);
              return google.maps.event.addListener(marker, "click", function() {
                if (openInfoWindow) {
                  openInfoWindow.close();
                }
                infoWindow.open(map, marker);
                openInfoWindow = infoWindow;
              });
            });
          });
        });
        familiesSorted.sort();
        _.each(familiesSorted, function(family) {
          return $('#menu-content-families').append("<div class=\"family-row\"><div class=\"checkbox family selected\"><i class=\"icon-ok\"></i></div><div class='title'>" + family + "</div></div>");
        });
        $('#menu-content-families .family-row').on('click', function() {
          var family;
          family = families[$(this).find('.title').html()];
          if ($(this).find('.checkbox').hasClass('selected')) {
            $(this).find('.checkbox').removeClass('selected');
            return _.each(family.markers, function(marker) {
              return marker.setMap(null);
            });
          } else {
            $(this).find('.checkbox').addClass('selected');
            return _.each(family.markers, function(marker) {
              return marker.setMap(map);
            });
          }
        });
        $('#family-select-all').on('click', function() {
          $('.checkbox.family').addClass('selected');
          return _.each(families, function(family) {
            return _.each(family.markers, function(marker) {
              return marker.setMap(map);
            });
          });
        });
        $('#family-unselect-all').on('click', function() {
          $('.checkbox.family').removeClass('selected');
          return _.each(families, function(family) {
            return _.each(family.markers, function(marker) {
              return marker.setMap(null);
            });
          });
        });
        $('#menu-content-list .list-row').on('click', function() {
          return showOverlay();
        });
        $('#overlay-close').on('click', function() {
          return hideOverlay();
        });
        $('#popover-inner').on('click', function(e) {
          e.stopPropagation();
          return false;
        });
        $('#popover-outer').on('click', function() {
          return hideOverlay();
        });
        $('#tab-button-families').on('click', function() {
          if (!$(this).hasClass('selected')) {
            $('.tab-button.selected').removeClass('selected');
            $(this).addClass('selected');
            return $('.menu-content-container').animate({
              left: 0
            }, 200);
          }
        });
        $('#tab-button-trails').on('click', function() {
          if (!$(this).hasClass('selected')) {
            $('.tab-button.selected').removeClass('selected');
            $(this).addClass('selected');
            return $('.menu-content-container').animate({
              left: -300
            }, 200);
          }
        });
        return $('#tab-button-list').on('click', function() {
          if (!$(this).hasClass('selected')) {
            $('.tab-button.selected').removeClass('selected');
            $(this).addClass('selected');
            return $('.menu-content-container').animate({
              left: -600
            }, 200);
          }
        });
      }, 'json');
      return $.get("json/trails.json", function(json) {
        trails = jQuery.extend(true, {}, json);
        _.each(json, function(trail, key) {
          return $('#menu-content-trails').append("<div class=\"family-row\"><div class=\"checkbox trail\"><i class=\"icon-ok\"></i></div><div class=\"title\">" + key + "</div></div>");
        });
        return $('#menu-content-trails .family-row').on('click', function() {
          var species;
          if (!$(this).find('.checkbox').hasClass('selected')) {
            $('#menu-content-trails .family-row .checkbox').removeClass('selected');
            _.each(markers, function(marker) {
              return marker.marker.setMap(null);
            });
            species = trails[$(this).find('.title').html()].split('; ');
            _.each(species, function(current) {
              return _.each(markers, function(marker) {
                if (marker.species === current.toLowerCase()) {
                  return marker.marker.setMap(map);
                }
              });
            });
            return $(this).find('.checkbox').addClass('selected');
          } else {
            $(this).find('.checkbox').removeClass('selected');
            return _.each(markers, function(marker) {
              return marker.marker.setMap(map);
            });
          }
        });
      }, 'json');
    };
    google.maps.event.addDomListener(window, "load", initialize);
    $('#expand-menu').on('click', function() {
      $('#expand-menu').toggleClass('selected');
      return $('#inner-container').toggleClass('menu-visible');
    });
    $('#mapview-satellite').on('click', function() {
      if (!$('#mapview-satellite').hasClass('selected')) {
        map.setMapTypeId(google.maps.MapTypeId.SATELLITE);
        $('#mapview-standard').removeClass('selected');
        return $('#mapview-satellite').addClass('selected');
      }
    });
    return $('#mapview-standard').on('click', function() {
      var zoom;
      if (!$('#mapview-standard').hasClass('selected')) {
        zoom = map.getZoom();
        map.setMapTypeId(google.maps.MapTypeId.ROADMAP);
        $('#mapview-satellite').removeClass('selected');
        $('#mapview-standard').addClass('selected');
        return map.setZoom(zoom);
      }
    });
  });

}).call(this);
